name: Test Coveralls

on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Generate test coverage
        run: |
          npm ci
          npm coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}